var searchData=
[
  ['tabla_20comparativa_3a_20patrones_20y_20problemas_20que_20resuelven_0',['1. Tabla Comparativa: Patrones y Problemas que Resuelven',['../md_planning_2design-pattern.html#autotoc_md13',1,'']]],
  ['template_20factory_20method_1',['3. Template + Factory Method',['../md_planning_2design-pattern.html#autotoc_md34',1,'']]],
  ['template_20y_20factory_20method_2',['3. Patrones Template y Factory Method',['../md_planning_2ulm-diagrams.html#autotoc_md119',1,'']]],
  ['template_20y_20factory_20method_20extensibilidad_20de_20componentes_20físicos_3',['4. Patrones Template y Factory Method - Extensibilidad de Componentes Físicos',['../md_planning_2design-pattern.html#autotoc_md20',1,'']]],
  ['test_5f1d_5fsimulation_4',['test_1d_simulation',['../namespacetest__integration.html#afd7f36b5b2f7ad67040a6b21c1eee2d1',1,'test_integration']]],
  ['test_5fintegration_5',['test_integration',['../namespacetest__integration.html',1,'']]],
  ['test_5fintegration_2epy_6',['test_integration.py',['../test__integration_8py.html',1,'']]],
  ['tests_20tt_7',['&lt;tt&gt;tests/&lt;/tt&gt;',['../md_planning_2structure.html#autotoc_md110',1,'']]],
  ['the_20c_20backend_20strong_8',['&lt;strong&gt;A. Physics Engine Core (The C++ Backend)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md72',1,'']]],
  ['the_20system_20em_20must_20do_20em_20strong_9',['&lt;strong&gt;2. Functional Requirements (What the System &lt;em&gt;Must Do&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md71',1,'']]],
  ['the_20system_20em_20must_20produce_20em_20strong_10',['&lt;strong&gt;C. Outputs and Analysis (What the System &lt;em&gt;Must Produce&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md74',1,'']]],
  ['the_20system_20performs_20strong_11',['&lt;strong&gt;3. Non-Functional Requirements (How &lt;em&gt;Well&lt;/em&gt; the System Performs)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md77',1,'']]],
  ['the_20user_20interface_20strong_12',['&lt;strong&gt;B. Python API (The User Interface)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md73',1,'']]],
  ['time_5fstep_13',['time_step',['../classdirac__solver_1_1core_1_1SimulationProblem.html#a9a6db345ab47e7b1a192e9eb649dc6f3',1,'dirac_solver::core::SimulationProblem']]],
  ['timeintegrator_14',['TimeIntegrator',['../classTimeIntegrator.html',1,'']]],
  ['timeintegrator_2eh_15',['TimeIntegrator.h',['../TimeIntegrator_8h.html',1,'']]],
  ['top_5flevel_2etxt_16',['top_level.txt',['../top__level_8txt.html',1,'']]],
  ['total_5ftime_17',['total_time',['../classdirac__solver_1_1core_1_1SimulationProblem.html#a8a595e2391e5e389c9880b90e8426c8f',1,'dirac_solver::core::SimulationProblem']]],
  ['trozos_20efecto_20klein_18',['3. Potencial a Trozos (Efecto Klein)',['../md_planning_2problems-to-solve.html#autotoc_md53',1,'']]],
  ['tt_20_5f_5finit_5f_5f_20py_20tt_19',['2. Nuevas constantes globales definidas en &lt;tt&gt;__init__.py&lt;/tt&gt;',['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md9',1,'']]],
  ['tt_20conditions_20tt_20–_20condiciones_20',['5. &lt;tt&gt;conditions/&lt;/tt&gt; – Condiciones',['../md_planning_2structure.html#autotoc_md105',1,'']]],
  ['tt_20constants_20py_20tt_21',['1. Eliminación de &lt;tt&gt;constants.py&lt;/tt&gt;',['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md8',1,'']]],
  ['tt_20docs_20tt_22',['&lt;tt&gt;docs/&lt;/tt&gt;',['../md_planning_2structure.html#autotoc_md114',1,'']]],
  ['tt_20examples_20tt_23',['&lt;tt&gt;examples/&lt;/tt&gt;',['../md_planning_2structure.html#autotoc_md112',1,'']]],
  ['tt_20geometry_20tt_20–_20geometrías_20y_20dominios_24',['4. &lt;tt&gt;geometry/&lt;/tt&gt; – Geometrías y dominios',['../md_planning_2structure.html#autotoc_md104',1,'']]],
  ['tt_20io_20tt_20–_20entrada_20salida_25',['6. &lt;tt&gt;io/&lt;/tt&gt; – Entrada/Salida',['../md_planning_2structure.html#autotoc_md106',1,'']]],
  ['tt_20physics_20tt_20–_20definiciones_20físicas_26',['2. &lt;tt&gt;physics/&lt;/tt&gt; – Definiciones físicas',['../md_planning_2structure.html#autotoc_md102',1,'']]],
  ['tt_20potentials_20tt_20–_20potenciales_27',['3. &lt;tt&gt;potentials/&lt;/tt&gt; – Potenciales',['../md_planning_2structure.html#autotoc_md103',1,'']]],
  ['tt_20solvers_20tt_20–_20núcleo_20numérico_28',['1. &lt;tt&gt;solvers/&lt;/tt&gt; – Núcleo numérico',['../md_planning_2structure.html#autotoc_md101',1,'']]],
  ['tt_20src_20dirac_5fsolver_20tt_29',['&lt;tt&gt;src/dirac_solver/&lt;/tt&gt;',['../md_planning_2structure.html#autotoc_md100',1,'']]],
  ['tt_20tests_20tt_30',['&lt;tt&gt;tests/&lt;/tt&gt;',['../md_planning_2structure.html#autotoc_md110',1,'']]],
  ['tt_20utils_20tt_20–_20utilidades_20generales_31',['8. &lt;tt&gt;utils/&lt;/tt&gt; – Utilidades generales',['../md_planning_2structure.html#autotoc_md108',1,'']]],
  ['tt_20visualization_20tt_20–_20gráficos_20y_20análisis_32',['7. &lt;tt&gt;visualization/&lt;/tt&gt; – Gráficos y análisis',['../md_planning_2structure.html#autotoc_md107',1,'']]]
];
