var searchData=
[
  ['paquete_20gaussiano_0',['Paquete Gaussiano',['..//home/sebastian/Documents/Desarrollo/Desarrollo/dirac_solver/planning/spinor-definition.md#autotoc_md111',1,'']]],
  ['parámetros_20de_20entrada_1',['parámetros de entrada',['../md_planning_2problems-to-solve.html#autotoc_md64',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md69',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md74',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md79',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md84',1,'Parámetros de Entrada']]],
  ['para_20la_20arquitectura_20de_20dirac_5fsolver_2',['Diagramas UML para la Arquitectura de dirac_solver',['../md_planning_2ulm-diagrams.html',1,'']]],
  ['para_20un_20solucionador_20de_20la_20ecuación_20de_20dirac_3',['Plan del Proyecto para un Solucionador de la Ecuación de Dirac',['../md_planning_2problems-to-solve.html',1,'']]],
  ['partícula_20libre_4',['1. Partícula Libre',['../md_planning_2problems-to-solve.html#autotoc_md62',1,'']]],
  ['patrón_20adapter_5',['7. Patrón Adapter',['../md_planning_2ulm-diagrams.html#autotoc_md143',1,'']]],
  ['patrón_20adapter_20–_20interoperabilidad_20con_20librerías_20externas_6',['8. Patrón Adapter – Interoperabilidad con Librerías Externas',['../md_planning_2design-pattern.html#autotoc_md46',1,'']]],
  ['patrón_20builder_7',['patrón builder',['../md_planning_2ulm-diagrams.html#autotoc_md136',1,'1. Patrón Builder'],['../md_planning_2design-pattern.html#autotoc_md35',1,'API fluida gracias al Patrón Builder']]],
  ['patrón_20builder_20configuración_20de_20la_20simulación_8',['2. Patrón Builder - Configuración de la Simulación',['../md_planning_2design-pattern.html#autotoc_md34',1,'']]],
  ['patrón_20decorator_9',['6. Patrón Decorator',['../md_planning_2ulm-diagrams.html#autotoc_md141',1,'']]],
  ['patrón_20decorator_20–_20extensión_20dinámica_20de_20funcionalidades_10',['7. Patrón Decorator – Extensión Dinámica de Funcionalidades',['../md_planning_2design-pattern.html#autotoc_md44',1,'']]],
  ['patrón_20facade_11',['5. Patrón Facade',['../md_planning_2ulm-diagrams.html#autotoc_md140',1,'']]],
  ['patrón_20facade_20interfaz_20simplificada_20de_20i_20o_12',['6. Patrón Facade - Interfaz Simplificada de I/O',['../md_planning_2design-pattern.html#autotoc_md43',1,'']]],
  ['patrón_20observer_13',['4. Patrón Observer',['../md_planning_2ulm-diagrams.html#autotoc_md139',1,'']]],
  ['patrón_20observer_20visualización_20y_20monitoreo_14',['5. Patrón Observer - Visualización y Monitoreo',['../md_planning_2design-pattern.html#autotoc_md41',1,'']]],
  ['patrón_20strategy_15',['2. Patrón Strategy',['../md_planning_2ulm-diagrams.html#autotoc_md137',1,'']]],
  ['patrón_20strategy_20flexibilidad_20en_20los_20algoritmos_16',['3. Patrón Strategy - Flexibilidad en los Algoritmos',['../md_planning_2design-pattern.html#autotoc_md37',1,'']]],
  ['patrones_17',['9. Relaciones entre los Patrones',['../md_planning_2design-pattern.html#autotoc_md48',1,'']]],
  ['patrones_20de_20diseño_20de_20dirac_5fsolver_18',['Arquitectura y Patrones de Diseño de dirac_solver',['../md_planning_2design-pattern.html',1,'']]],
  ['patrones_20template_20y_20factory_20method_19',['3. Patrones Template y Factory Method',['../md_planning_2ulm-diagrams.html#autotoc_md138',1,'']]],
  ['patrones_20template_20y_20factory_20method_20extensibilidad_20de_20componentes_20físicos_20',['4. Patrones Template y Factory Method - Extensibilidad de Componentes Físicos',['../md_planning_2design-pattern.html#autotoc_md39',1,'']]],
  ['patrones_20y_20problemas_20que_20resuelven_21',['1. Tabla Comparativa: Patrones y Problemas que Resuelven',['../md_planning_2design-pattern.html#autotoc_md32',1,'']]],
  ['pauli_20general_22',['Construcción del Espinor de Pauli General',['../md_planning_2spinor-definition.html',1,'']]],
  ['pauli_5fspinor_23',['pauli_spinor',['../classdirac__solver_1_1initial__state_1_1ConstantSpinor.html#ab1336ddbd7b42dd830a21b66d156bc57',1,'dirac_solver::initial_state::ConstantSpinor']]],
  ['performance_20requirements_20optional_20strong_24',['&lt;strong&gt;D Advanced Performance Requirements (Optional)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md94',1,'']]],
  ['performs_20strong_25',['&lt;strong&gt;3. Non-Functional Requirements (How &lt;em&gt;Well&lt;/em&gt; the System Performs)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md96',1,'']]],
  ['periodicboundary_26',['PeriodicBoundary',['../classPeriodicBoundary.html',1,'']]],
  ['periodicboundary_2eh_27',['PeriodicBoundary.h',['../PeriodicBoundary_8h.html',1,'']]],
  ['permanent_20ban_28',['4. Permanent Ban',['../md_CODE__OF__CONDUCT.html#autotoc_md10',1,'']]],
  ['physics_20engine_20core_20the_20c_20backend_20strong_29',['&lt;strong&gt;A. Physics Engine Core (The C++ Backend)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md91',1,'']]],
  ['physics_20tt_20–_20definiciones_20físicas_30',['2. &lt;tt&gt;physics/&lt;/tt&gt; – Definiciones físicas',['../md_planning_2structure.html#autotoc_md121',1,'']]],
  ['pipy_31',['Instalación mediante pipy',['../index.html#autotoc_md151',1,'']]],
  ['plan_20del_20proyecto_20para_20un_20solucionador_20de_20la_20ecuación_20de_20dirac_32',['Plan del Proyecto para un Solucionador de la Ecuación de Dirac',['../md_planning_2problems-to-solve.html',1,'']]],
  ['planewave_33',['PlaneWave',['../classdirac__solver_1_1initial__state_1_1PlaneWave.html',1,'dirac_solver::initial_state']]],
  ['platform_5fid_34',['PLATFORM_ID',['../CMakeCXXCompilerId_8cpp.html#adbc5372f40838899018fadbc89bd588b',1,'CMakeCXXCompilerId.cpp']]],
  ['pledge_35',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md1',1,'']]],
  ['plot_5fprobability_5fdensity_36',['plot_probability_density',['../classdirac__solver_1_1core_1_1DiracSolver.html#a2229ba14dd2f6ea676473439298afec6',1,'dirac_solver::core::DiracSolver']]],
  ['potencial_20a_20trozos_20efecto_20klein_37',['3. Potencial a Trozos (Efecto Klein)',['../md_planning_2problems-to-solve.html#autotoc_md72',1,'']]],
  ['potencial_20central_20interacción_20de_20coulomb_38',['4. Potencial Central (Interacción de Coulomb)',['../md_planning_2problems-to-solve.html#autotoc_md77',1,'']]],
  ['potencial_20de_20yukawa_39',['5. Potencial de Yukawa',['../md_planning_2problems-to-solve.html#autotoc_md82',1,'']]],
  ['potencial_20infinito_40',['2. Pozo de Potencial Infinito',['../md_planning_2problems-to-solve.html#autotoc_md67',1,'']]],
  ['potenciales_41',['3. &lt;tt&gt;potentials/&lt;/tt&gt; – Potenciales',['../md_planning_2structure.html#autotoc_md122',1,'']]],
  ['potential_42',['potential',['../classPotential.html',1,'Potential'],['../classdirac__solver_1_1core_1_1SimulationProblem.html#a46284a16440e1d5431c8a9ce6be5dbf4',1,'dirac_solver.core.SimulationProblem.potential']]],
  ['potential_2eh_43',['Potential.h',['../Potential_8h.html',1,'']]],
  ['potentials_20tt_20–_20potenciales_44',['3. &lt;tt&gt;potentials/&lt;/tt&gt; – Potenciales',['../md_planning_2structure.html#autotoc_md122',1,'']]],
  ['potentials_2epy_45',['potentials.py',['../potentials_8py.html',1,'']]],
  ['pozo_20de_20potencial_20infinito_46',['2. Pozo de Potencial Infinito',['../md_planning_2problems-to-solve.html#autotoc_md67',1,'']]],
  ['presentation_20structure_3a_20requirements_20engineering_20for_20a_20dirac_20equation_20solver_47',['Presentation Structure: Requirements Engineering for a Dirac Equation Solver',['../md_planning_2requirements-engineering.html',1,'']]],
  ['principales_48',['principales',['../classFDTDLeapfrogIntegrator.html#autotoc_md20',1,'Características principales'],['../index.html#autotoc_md146',1,'Características principales']]],
  ['probability_5fcurrent_49',['probability_current',['../classdirac__solver_1_1observables_1_1Observables.html#a3f323b463add5b5fda900f63d17e7a5e',1,'dirac_solver::observables::Observables']]],
  ['probability_5fdensity_50',['probability_density',['../classdirac__solver_1_1observables_1_1Observables.html#aad5d0f2fe724f9cbed157f5211e6f73e',1,'dirac_solver::observables::Observables']]],
  ['problem_51',['problem',['../classdirac__solver_1_1core_1_1DiracSolver.html#af240a269184ddc9bd163e575066add96',1,'dirac_solver.core.DiracSolver.problem'],['../classdirac__solver_1_1storage_1_1HDF5Storage.html#ab0824585814a33ce51b9c37379f617f8',1,'dirac_solver.storage.HDF5Storage.problem']]],
  ['problem_20statement_20scope_20strong_52',['&lt;strong&gt;1. Introduction: Problem Statement &amp; Scope&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md88',1,'']]],
  ['problema_53',['problema',['../md_planning_2problems-to-solve.html#autotoc_md83',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md78',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md73',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md68',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md63',1,'Descripción del Problema']]],
  ['problemas_20que_20resuelven_54',['1. Tabla Comparativa: Patrones y Problemas que Resuelven',['../md_planning_2design-pattern.html#autotoc_md32',1,'']]],
  ['problems_2dto_2dsolve_2emd_55',['problems-to-solve.md',['../problems-to-solve_8md.html',1,'']]],
  ['produce_20em_20strong_56',['&lt;strong&gt;C. Outputs and Analysis (What the System &lt;em&gt;Must Produce&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md93',1,'']]],
  ['project_20management_20requirements_20strong_57',['&lt;strong&gt;5. Project Management Requirements&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md100',1,'']]],
  ['proyecto_58',['proyecto',['../index.html#autotoc_md148',1,'Estructura del proyecto'],['../md_planning_2structure.html#autotoc_md117',1,'Raíz del Proyecto']]],
  ['proyecto_20dirac_5fsolver_59',['Estructura del Proyecto dirac_solver',['../md_planning_2structure.html',1,'']]],
  ['proyecto_20para_20un_20solucionador_20de_20la_20ecuación_20de_20dirac_60',['Plan del Proyecto para un Solucionador de la Ecuación de Dirac',['../md_planning_2problems-to-solve.html',1,'']]],
  ['psi_20t_20delta_20t_61',['Inicialización de \(\psi(t - \Delta t)\)',['../classFDTDLeapfrogIntegrator.html#autotoc_md22',1,'']]],
  ['psi_5fdataset_62',['psi_dataset',['../classdirac__solver_1_1storage_1_1HDF5Storage.html#afbd3c857786cde437f8ff54a46fab3c0',1,'dirac_solver::storage::HDF5Storage']]],
  ['pull_20requests_63',['Contribuir con Código (Pull Requests)',['../md_CONTRIBUTING.html#autotoc_md15',1,'']]],
  ['py_20tt_64',['py tt',['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md27',1,'1. Eliminación de &lt;tt&gt;constants.py&lt;/tt&gt;'],['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md28',1,'2. Nuevas constantes globales definidas en &lt;tt&gt;__init__.py&lt;/tt&gt;']]],
  ['pyboundarycondition_65',['PyBoundaryCondition',['../classPyBoundaryCondition.html',1,'']]],
  ['pypotential_66',['PyPotential',['../classPyPotential.html',1,'']]],
  ['python_67',['Ejemplo (en Python)',['../classScalarPotential.html#autotoc_md19',1,'']]],
  ['python_20api_20the_20user_20interface_20strong_68',['&lt;strong&gt;B. Python API (The User Interface)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md92',1,'']]],
  ['pytimeintegrator_69',['PyTimeIntegrator',['../classPyTimeIntegrator.html',1,'']]]
];
