var searchData=
[
  ['d_20advanced_20performance_20requirements_20optional_20strong_0',['&lt;strong&gt;D Advanced Performance Requirements (Optional)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md75',1,'']]],
  ['de_20componentes_20físicos_1',['4. Patrones Template y Factory Method - Extensibilidad de Componentes Físicos',['../md_planning_2design-pattern.html#autotoc_md20',1,'']]],
  ['de_20coulomb_2',['4. Potencial Central (Interacción de Coulomb)',['../md_planning_2problems-to-solve.html#autotoc_md58',1,'']]],
  ['de_20dirac_5fsolver_3',['Diagramas UML para la Arquitectura de dirac_solver',['../md_planning_2ulm-diagrams.html',1,'']]],
  ['de_20diseño_20de_20dirac_5fsolver_4',['Arquitectura y Patrones de Diseño de dirac_solver',['../md_planning_2design-pattern.html',1,'']]],
  ['de_20entrada_5',['de entrada',['../md_planning_2problems-to-solve.html#autotoc_md65',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md60',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md45',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md50',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md55',1,'Parámetros de Entrada']]],
  ['de_20funcionalidades_6',['7. Patrón Decorator – Extensión Dinámica de Funcionalidades',['../md_planning_2design-pattern.html#autotoc_md25',1,'']]],
  ['de_20i_20o_7',['6. Patrón Facade - Interfaz Simplificada de I/O',['../md_planning_2design-pattern.html#autotoc_md24',1,'']]],
  ['de_20la_20base_8',['Espinores de la Base',['../md_planning_2spinor-definition.html#autotoc_md85',1,'']]],
  ['de_20la_20ecuación_20de_20dirac_9',['de la ecuación de dirac',['../index.html',1,'Dirac-Solver: Solucionador numérico de la Ecuación de Dirac.'],['../md_planning_2problems-to-solve.html',1,'Plan del Proyecto para un Solucionador de la Ecuación de Dirac']]],
  ['de_20la_20librería_20dirac_20solver_10',['Actualización de la librería Dirac Solver',['../md_planning_2Actualizaci_xC3_xB3n__constants.html',1,'']]],
  ['de_20la_20simulación_11',['2. Patrón Builder - Configuración de la Simulación',['../md_planning_2design-pattern.html#autotoc_md15',1,'']]],
  ['de_20los_20ángulos_12',['Definiciones de los Ángulos',['../md_planning_2spinor-definition.html#autotoc_md86',1,'']]],
  ['de_20pauli_20general_13',['Construcción del Espinor de Pauli General',['../md_planning_2spinor-definition.html',1,'']]],
  ['de_20potencial_20infinito_14',['2. Pozo de Potencial Infinito',['../md_planning_2problems-to-solve.html#autotoc_md48',1,'']]],
  ['de_20tt_20constants_20py_20tt_15',['1. Eliminación de &lt;tt&gt;constants.py&lt;/tt&gt;',['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md8',1,'']]],
  ['de_20uso_16',['Ejemplo de uso',['../classAbsorbingBoundary.html#autotoc_md0',1,'']]],
  ['de_20yukawa_17',['5. Potencial de Yukawa',['../md_planning_2problems-to-solve.html#autotoc_md63',1,'']]],
  ['decorator_18',['decorator',['../md_planning_2design-pattern.html#autotoc_md37',1,'6. Decorator'],['../md_planning_2ulm-diagrams.html#autotoc_md122',1,'6. Patrón Decorator']]],
  ['decorator_20–_20extensión_20dinámica_20de_20funcionalidades_19',['7. Patrón Decorator – Extensión Dinámica de Funcionalidades',['../md_planning_2design-pattern.html#autotoc_md25',1,'']]],
  ['definiciones_20de_20los_20ángulos_20',['Definiciones de los Ángulos',['../md_planning_2spinor-definition.html#autotoc_md86',1,'']]],
  ['definiciones_20físicas_21',['2. &lt;tt&gt;physics/&lt;/tt&gt; – Definiciones físicas',['../md_planning_2structure.html#autotoc_md102',1,'']]],
  ['definidas_20en_20tt_20_5f_5finit_5f_5f_20py_20tt_22',['2. Nuevas constantes globales definidas en &lt;tt&gt;__init__.py&lt;/tt&gt;',['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md9',1,'']]],
  ['del_20espinor_20de_20pauli_20general_23',['Construcción del Espinor de Pauli General',['../md_planning_2spinor-definition.html',1,'']]],
  ['del_20problema_24',['del problema',['../md_planning_2problems-to-solve.html#autotoc_md44',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md59',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md64',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md49',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md54',1,'Descripción del Problema']]],
  ['del_20proyecto_25',['Raíz del Proyecto',['../md_planning_2structure.html#autotoc_md98',1,'']]],
  ['del_20proyecto_20dirac_5fsolver_26',['Estructura del Proyecto dirac_solver',['../md_planning_2structure.html',1,'']]],
  ['del_20proyecto_20para_20un_20solucionador_20de_20la_20ecuación_20de_20dirac_27',['Plan del Proyecto para un Solucionador de la Ecuación de Dirac',['../md_planning_2problems-to-solve.html',1,'']]],
  ['dependency_5flinks_2etxt_28',['dependency_links.txt',['../dependency__links_8txt.html',1,'']]],
  ['descartadas_29',['10. Alternativas Consideradas y Descartadas',['../md_planning_2design-pattern.html#autotoc_md31',1,'']]],
  ['descripción_20del_20problema_30',['descripción del problema',['../md_planning_2problems-to-solve.html#autotoc_md59',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md44',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md64',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md49',1,'Descripción del Problema'],['../md_planning_2problems-to-solve.html#autotoc_md54',1,'Descripción del Problema']]],
  ['design_2dpattern_2emd_31',['design-pattern.md',['../design-pattern_8md.html',1,'']]],
  ['diagramas_20uml_20para_20la_20arquitectura_20de_20dirac_5fsolver_32',['Diagramas UML para la Arquitectura de dirac_solver',['../md_planning_2ulm-diagrams.html',1,'']]],
  ['dim_33',['dim',['../classdirac__solver_1_1geometry_1_1Grid.html#a015c3ec7ba74fddfa326bde8a1b27cb6',1,'dirac_solver::geometry::Grid']]],
  ['dinámica_20de_20funcionalidades_34',['7. Patrón Decorator – Extensión Dinámica de Funcionalidades',['../md_planning_2design-pattern.html#autotoc_md25',1,'']]],
  ['dirac_35',['dirac',['../namespaceDirac.html',1,'Dirac'],['../md_planning_2problems-to-solve.html',1,'Plan del Proyecto para un Solucionador de la Ecuación de Dirac']]],
  ['dirac_20equation_20solver_36',['Presentation Structure: Requirements Engineering for a Dirac Equation Solver',['../md_planning_2requirements-engineering.html',1,'']]],
  ['dirac_20solver_37',['Actualización de la librería Dirac Solver',['../md_planning_2Actualizaci_xC3_xB3n__constants.html',1,'']]],
  ['dirac_20solver_3a_20solucionador_20numérico_20de_20la_20ecuación_20de_20dirac_38',['Dirac-Solver: Solucionador numérico de la Ecuación de Dirac.',['../index.html',1,'']]],
  ['dirac_5fsolver_39',['dirac_solver',['../md_planning_2design-pattern.html',1,'Arquitectura y Patrones de Diseño de dirac_solver'],['../md_planning_2ulm-diagrams.html',1,'Diagramas UML para la Arquitectura de dirac_solver'],['../namespacedirac__solver.html',1,'dirac_solver'],['../md_planning_2structure.html',1,'Estructura del Proyecto dirac_solver']]],
  ['dirac_5fsolver_20tt_40',['&lt;tt&gt;src/dirac_solver/&lt;/tt&gt;',['../md_planning_2structure.html#autotoc_md100',1,'']]],
  ['dirac_5fsolver_3a_3acore_41',['core',['../namespacedirac__solver_1_1core.html',1,'dirac_solver']]],
  ['dirac_5fsolver_3a_3ageometry_42',['geometry',['../namespacedirac__solver_1_1geometry.html',1,'dirac_solver']]],
  ['dirac_5fsolver_3a_3ainitial_5fstate_43',['initial_state',['../namespacedirac__solver_1_1initial__state.html',1,'dirac_solver']]],
  ['diracmatrices_2eh_44',['DiracMatrices.h',['../DiracMatrices_8h.html',1,'']]],
  ['diracproblembuilder_45',['DiracProblemBuilder',['../classdirac__solver_1_1core_1_1DiracProblemBuilder.html',1,'dirac_solver::core']]],
  ['diracsolver_46',['DiracSolver',['../classdirac__solver_1_1core_1_1DiracSolver.html',1,'dirac_solver::core']]],
  ['diseño_20de_20dirac_5fsolver_47',['Arquitectura y Patrones de Diseño de dirac_solver',['../md_planning_2design-pattern.html',1,'']]],
  ['do_20em_20strong_48',['&lt;strong&gt;2. Functional Requirements (What the System &lt;em&gt;Must Do&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md71',1,'']]],
  ['docs_20tt_49',['&lt;tt&gt;docs/&lt;/tt&gt;',['../md_planning_2structure.html#autotoc_md114',1,'']]],
  ['documentación_50',['Documentación',['../index.html#autotoc_md127',1,'']]],
  ['dominios_51',['4. &lt;tt&gt;geometry/&lt;/tt&gt; – Geometrías y dominios',['../md_planning_2structure.html#autotoc_md104',1,'']]],
  ['dv_52',['dv',['../classdirac__solver_1_1geometry_1_1Grid.html#aa826a5837f24f73bb7ab5675cfdf34da',1,'dirac_solver::geometry::Grid']]]
];
