var searchData=
[
  ['ecuación_20de_20dirac_0',['ecuación de dirac',['../index.html',1,'Dirac-Solver: Solucionador numérico de la Ecuación de Dirac'],['../md_planning_2problems-to-solve.html',1,'Plan del Proyecto para un Solucionador de la Ecuación de Dirac']]],
  ['editable_1',['Instalación local editable',['../index.html#autotoc_md151',1,'']]],
  ['efecto_20klein_2',['3. Potencial a Trozos (Efecto Klein)',['../md_planning_2problems-to-solve.html#autotoc_md72',1,'']]],
  ['ejemplo_20en_20python_3',['Ejemplo (en Python)',['../classScalarPotential.html#autotoc_md19',1,'']]],
  ['ejemplos_4',['Ejemplos',['../index.html#autotoc_md153',1,'']]],
  ['electron_5fcharge_5',['electron_charge',['../namespacedirac__solver.html#af21fee2285001ff10259c82283a4fbc3',1,'dirac_solver']]],
  ['electron_5fmass_6',['electron_mass',['../namespacedirac__solver.html#a9fc036514e9aab2bd0b18502aafc5e13',1,'dirac_solver']]],
  ['eliminación_20de_20tt_20constants_20py_20tt_7',['1. Eliminación de &lt;tt&gt;constants.py&lt;/tt&gt;',['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md27',1,'']]],
  ['em_20must_20do_20em_20strong_8',['&lt;strong&gt;2. Functional Requirements (What the System &lt;em&gt;Must Do&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md90',1,'']]],
  ['em_20must_20produce_20em_20strong_9',['&lt;strong&gt;C. Outputs and Analysis (What the System &lt;em&gt;Must Produce&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md93',1,'']]],
  ['em_20well_20em_20the_20system_20performs_20strong_10',['&lt;strong&gt;3. Non-Functional Requirements (How &lt;em&gt;Well&lt;/em&gt; the System Performs)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md96',1,'']]],
  ['en_20los_20algoritmos_11',['3. Patrón Strategy - Flexibilidad en los Algoritmos',['../md_planning_2design-pattern.html#autotoc_md37',1,'']]],
  ['en_20python_12',['Ejemplo (en Python)',['../classScalarPotential.html#autotoc_md19',1,'']]],
  ['en_20tt_20_5f_5finit_5f_5f_20py_20tt_13',['2. Nuevas constantes globales definidas en &lt;tt&gt;__init__.py&lt;/tt&gt;',['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md28',1,'']]],
  ['enforcement_14',['Enforcement',['../md_CODE__OF__CONDUCT.html#autotoc_md5',1,'']]],
  ['enforcement_20guidelines_15',['Enforcement Guidelines',['../md_CODE__OF__CONDUCT.html#autotoc_md6',1,'']]],
  ['enforcement_20responsibilities_16',['Enforcement Responsibilities',['../md_CODE__OF__CONDUCT.html#autotoc_md3',1,'']]],
  ['engine_20core_20the_20c_20backend_20strong_17',['&lt;strong&gt;A. Physics Engine Core (The C++ Backend)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md91',1,'']]],
  ['engineering_20for_20a_20dirac_20equation_20solver_18',['Presentation Structure: Requirements Engineering for a Dirac Equation Solver',['../md_planning_2requirements-engineering.html',1,'']]],
  ['entorno_19',['1. Configura tu Entorno',['../md_CONTRIBUTING.html#autotoc_md16',1,'']]],
  ['entrada_20',['entrada',['../md_planning_2problems-to-solve.html#autotoc_md64',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md69',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md84',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md74',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md79',1,'Parámetros de Entrada']]],
  ['entrada_20salida_21',['6. &lt;tt&gt;io/&lt;/tt&gt; – Entrada/Salida',['../md_planning_2structure.html#autotoc_md125',1,'']]],
  ['entradas_22',['entradas',['../md_planning_2spinor-definition.html#autotoc_md102',1,'Entradas'],['..//home/sebastian/Documents/Desarrollo/Desarrollo/dirac_solver/planning/spinor-definition.md#autotoc_md112',1,'Entradas'],['..//home/sebastian/Documents/Desarrollo/Desarrollo/dirac_solver/planning/spinor-definition.md#autotoc_md108',1,'Entradas']]],
  ['entre_20los_20patrones_23',['9. Relaciones entre los Patrones',['../md_planning_2design-pattern.html#autotoc_md48',1,'']]],
  ['envía_20tus_20cambios_24',['3. Envía tus Cambios',['../md_CONTRIBUTING.html#autotoc_md18',1,'']]],
  ['equation_20solver_25',['Presentation Structure: Requirements Engineering for a Dirac Equation Solver',['../md_planning_2requirements-engineering.html',1,'']]],
  ['errores_20bugs_20y_20sugerencias_26',['Reporte de Errores (Bugs) y Sugerencias',['../md_CONTRIBUTING.html#autotoc_md14',1,'']]],
  ['espinor_20constante_27',['Espinor Constante',['..//home/sebastian/Documents/Desarrollo/Desarrollo/dirac_solver/planning/spinor-definition.md#autotoc_md107',1,'']]],
  ['espinor_20de_20pauli_20general_28',['Construcción del Espinor de Pauli General',['../md_planning_2spinor-definition.html',1,'']]],
  ['espinores_20de_20la_20base_29',['Espinores de la Base',['../md_planning_2spinor-definition.html#autotoc_md104',1,'']]],
  ['esquema_20visual_30',['📂 Esquema Visual',['../md_planning_2structure.html#autotoc_md116',1,'']]],
  ['estructura_20del_20proyecto_31',['Estructura del proyecto',['../index.html#autotoc_md148',1,'']]],
  ['estructura_20del_20proyecto_20dirac_5fsolver_32',['Estructura del Proyecto dirac_solver',['../md_planning_2structure.html',1,'']]],
  ['evaluate_33',['evaluate',['../classFreeParticle.html#a19b24bf80dcc7268816c455674c0c9c4',1,'FreeParticle::evaluate()'],['../classdirac__solver_1_1initial__state_1_1InitialState.html#a36b97a28c145c7528ca064fcdcca2c0d',1,'dirac_solver.initial_state.InitialState.evaluate()'],['../classCoulombPotential.html#ae407d6cb33e69a230367685e05c09aaf',1,'CoulombPotential::evaluate()'],['../classInfiniteWellPotential.html#ad1924b35ab5862696257dda1a2669c6e',1,'InfiniteWellPotential::evaluate()'],['../classPotential.html#a32efd5ee677886223026061411b65538',1,'Potential::evaluate()'],['../classScalarPotential.html#a973bf456bbbcd628816de50515d330fe',1,'ScalarPotential::evaluate()'],['../classYukawaPotential.html#a0c3d693ed2370c69b2fca9560bed84dd',1,'YukawaPotential::evaluate()'],['../classdirac__solver_1_1initial__state_1_1PlaneWave.html#aefbaec4f8e32a004cb5ae27ae4331efd',1,'dirac_solver.initial_state.PlaneWave.evaluate()'],['../classdirac__solver_1_1initial__state_1_1GaussianPacket.html#a316c915e47f47aaeb218a90915ab8499',1,'dirac_solver.initial_state.GaussianPacket.evaluate()']]],
  ['evaluate_5fon_5fgrid_34',['evaluate_on_grid',['../classdirac__solver_1_1initial__state_1_1PlaneWave.html#ae57896d9c51d94ea0197bec431e02421',1,'dirac_solver.initial_state.PlaneWave.evaluate_on_grid()'],['../classdirac__solver_1_1initial__state_1_1GaussianPacket.html#a8cfb6b87a64c877fad6f430d9c169a1a',1,'dirac_solver.initial_state.GaussianPacket.evaluate_on_grid()'],['../classdirac__solver_1_1initial__state_1_1InitialState.html#a7743e20461f3c16df2d1f72896de67ee',1,'dirac_solver.initial_state.InitialState.evaluate_on_grid()']]],
  ['examples_20tt_35',['&lt;tt&gt;examples/&lt;/tt&gt;',['../md_planning_2structure.html#autotoc_md131',1,'']]],
  ['expected_5fvalue_5fenergy_36',['expected_value_energy',['../classdirac__solver_1_1observables_1_1Observables.html#af9b1adbff80e81210fa7a54064f78565',1,'dirac_solver::observables::Observables']]],
  ['expected_5fvalue_5fmomentum_37',['expected_value_momentum',['../classdirac__solver_1_1observables_1_1Observables.html#ad5dd0abafc1790dd3ffd1ba0068161c5',1,'dirac_solver::observables::Observables']]],
  ['expected_5fvalue_5fposition_38',['expected_value_position',['../classdirac__solver_1_1observables_1_1Observables.html#a3ef22480b236a5e20ad8d612193a333f',1,'dirac_solver::observables::Observables']]],
  ['extensión_20dinámica_20de_20funcionalidades_39',['7. Patrón Decorator – Extensión Dinámica de Funcionalidades',['../md_planning_2design-pattern.html#autotoc_md44',1,'']]],
  ['extensibilidad_20de_20componentes_20físicos_40',['4. Patrones Template y Factory Method - Extensibilidad de Componentes Físicos',['../md_planning_2design-pattern.html#autotoc_md39',1,'']]],
  ['externas_41',['8. Patrón Adapter – Interoperabilidad con Librerías Externas',['../md_planning_2design-pattern.html#autotoc_md46',1,'']]]
];
