var searchData=
[
  ['a_20dirac_20equation_20solver_0',['Presentation Structure: Requirements Engineering for a Dirac Equation Solver',['../md_planning_2requirements-engineering.html',1,'']]],
  ['a_20physics_20engine_20core_20the_20c_20backend_20strong_1',['&lt;strong&gt;A. Physics Engine Core (The C++ Backend)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md72',1,'']]],
  ['a_20trozos_20efecto_20klein_2',['3. Potencial a Trozos (Efecto Klein)',['../md_planning_2problems-to-solve.html#autotoc_md53',1,'']]],
  ['absorbingboundary_3',['absorbingboundary',['../classAbsorbingBoundary.html#afa1eb9ef1855a32e0e9ab87e5082346e',1,'AbsorbingBoundary::AbsorbingBoundary()'],['../classAbsorbingBoundary.html',1,'AbsorbingBoundary']]],
  ['absorbingboundary_2eh_4',['AbsorbingBoundary.h',['../AbsorbingBoundary_8h.html',1,'']]],
  ['actualización_20de_20la_20librería_20dirac_20solver_5',['Actualización de la librería Dirac Solver',['../md_planning_2Actualizaci_xC3_xB3n__constants.html',1,'']]],
  ['actualización_5fconstants_2emd_6',['Actualización_constants.md',['../Actualizaci_xC3_xB3n__constants_8md.html',1,'']]],
  ['adapter_7',['adapter',['../md_planning_2design-pattern.html#autotoc_md38',1,'7. Adapter'],['../md_planning_2ulm-diagrams.html#autotoc_md124',1,'7. Patrón Adapter']]],
  ['adapter_20–_20interoperabilidad_20con_20librerías_20externas_8',['8. Patrón Adapter – Interoperabilidad con Librerías Externas',['../md_planning_2design-pattern.html#autotoc_md27',1,'']]],
  ['advanced_20performance_20requirements_20optional_20strong_9',['&lt;strong&gt;D Advanced Performance Requirements (Optional)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md75',1,'']]],
  ['al_20patrón_20builder_10',['API fluida gracias al Patrón Builder',['../md_planning_2design-pattern.html#autotoc_md16',1,'']]],
  ['algoritmos_11',['3. Patrón Strategy - Flexibilidad en los Algoritmos',['../md_planning_2design-pattern.html#autotoc_md18',1,'']]],
  ['alpha_5fx_12',['alpha_x',['../namespaceDirac.html#a220c778fcf6de926d905379ca36d7b81',1,'Dirac']]],
  ['alpha_5fy_13',['alpha_y',['../namespaceDirac.html#a1ee219a1bed9ad5012b3ef6ba2f5e381',1,'Dirac']]],
  ['alpha_5fz_14',['alpha_z',['../namespaceDirac.html#a21dac9d07b94f2221878134ce3951549',1,'Dirac']]],
  ['alternativas_20consideradas_20y_20descartadas_15',['10. Alternativas Consideradas y Descartadas',['../md_planning_2design-pattern.html#autotoc_md31',1,'']]],
  ['análisis_16',['7. &lt;tt&gt;visualization/&lt;/tt&gt; – Gráficos y análisis',['../md_planning_2structure.html#autotoc_md107',1,'']]],
  ['analysis_20what_20the_20system_20em_20must_20produce_20em_20strong_17',['&lt;strong&gt;C. Outputs and Analysis (What the System &lt;em&gt;Must Produce&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md74',1,'']]],
  ['and_20analysis_20what_20the_20system_20em_20must_20produce_20em_20strong_18',['&lt;strong&gt;C. Outputs and Analysis (What the System &lt;em&gt;Must Produce&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md74',1,'']]],
  ['api_20fluida_20gracias_20al_20patrón_20builder_19',['API fluida gracias al Patrón Builder',['../md_planning_2design-pattern.html#autotoc_md16',1,'']]],
  ['api_20the_20user_20interface_20strong_20',['&lt;strong&gt;B. Python API (The User Interface)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md73',1,'']]],
  ['apply_21',['apply',['../classAbsorbingBoundary.html#a5338d859c3ed9140e3b202156f645726',1,'AbsorbingBoundary::apply()'],['../classBoundaryCondition.html#a89c213d7d45fd7fdaed4021a030ea998',1,'BoundaryCondition::apply()'],['../classPeriodicBoundary.html#ad1ac4291a92b159e061fc99e7777d34b',1,'PeriodicBoundary::apply()']]],
  ['architectural_20requirements_20strong_22',['&lt;strong&gt;4. System &amp; Architectural Requirements&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md79',1,'']]],
  ['arquitectura_20de_20dirac_5fsolver_23',['Diagramas UML para la Arquitectura de dirac_solver',['../md_planning_2ulm-diagrams.html',1,'']]],
  ['arquitectura_20y_20patrones_20de_20diseño_20de_20dirac_5fsolver_24',['Arquitectura y Patrones de Diseño de dirac_solver',['../md_planning_2design-pattern.html',1,'']]]
];
