var searchData=
[
  ['ecuación_20de_20dirac_0',['ecuación de dirac',['../index.html',1,'Dirac-Solver: Solucionador numérico de la Ecuación de Dirac.'],['../md_planning_2problems-to-solve.html',1,'Plan del Proyecto para un Solucionador de la Ecuación de Dirac']]],
  ['efecto_20klein_1',['3. Potencial a Trozos (Efecto Klein)',['../md_planning_2problems-to-solve.html#autotoc_md53',1,'']]],
  ['ejemplo_20de_20uso_2',['Ejemplo de uso',['../classAbsorbingBoundary.html#autotoc_md0',1,'']]],
  ['ejemplo_20en_20python_3',['Ejemplo (en Python)',['../classScalarPotential.html#autotoc_md1',1,'']]],
  ['electron_5fcharge_4',['electron_charge',['../namespacedirac__solver.html#af21fee2285001ff10259c82283a4fbc3',1,'dirac_solver']]],
  ['electron_5fmass_5',['electron_mass',['../namespacedirac__solver.html#a9fc036514e9aab2bd0b18502aafc5e13',1,'dirac_solver']]],
  ['eliminación_20de_20tt_20constants_20py_20tt_6',['1. Eliminación de &lt;tt&gt;constants.py&lt;/tt&gt;',['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md8',1,'']]],
  ['em_20must_20do_20em_20strong_7',['&lt;strong&gt;2. Functional Requirements (What the System &lt;em&gt;Must Do&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md71',1,'']]],
  ['em_20must_20produce_20em_20strong_8',['&lt;strong&gt;C. Outputs and Analysis (What the System &lt;em&gt;Must Produce&lt;/em&gt;)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md74',1,'']]],
  ['em_20well_20em_20the_20system_20performs_20strong_9',['&lt;strong&gt;3. Non-Functional Requirements (How &lt;em&gt;Well&lt;/em&gt; the System Performs)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md77',1,'']]],
  ['en_20los_20algoritmos_10',['3. Patrón Strategy - Flexibilidad en los Algoritmos',['../md_planning_2design-pattern.html#autotoc_md18',1,'']]],
  ['en_20python_11',['Ejemplo (en Python)',['../classScalarPotential.html#autotoc_md1',1,'']]],
  ['en_20tt_20_5f_5finit_5f_5f_20py_20tt_12',['2. Nuevas constantes globales definidas en &lt;tt&gt;__init__.py&lt;/tt&gt;',['../md_planning_2Actualizaci_xC3_xB3n__constants.html#autotoc_md9',1,'']]],
  ['engine_20core_20the_20c_20backend_20strong_13',['&lt;strong&gt;A. Physics Engine Core (The C++ Backend)&lt;/strong&gt;',['../md_planning_2requirements-engineering.html#autotoc_md72',1,'']]],
  ['engineering_20for_20a_20dirac_20equation_20solver_14',['Presentation Structure: Requirements Engineering for a Dirac Equation Solver',['../md_planning_2requirements-engineering.html',1,'']]],
  ['entrada_15',['entrada',['../md_planning_2problems-to-solve.html#autotoc_md55',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md50',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md45',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md60',1,'Parámetros de Entrada'],['../md_planning_2problems-to-solve.html#autotoc_md65',1,'Parámetros de Entrada']]],
  ['entrada_20salida_16',['6. &lt;tt&gt;io/&lt;/tt&gt; – Entrada/Salida',['../md_planning_2structure.html#autotoc_md106',1,'']]],
  ['entradas_17',['entradas',['..//home/sebastian/Documents/Desarrollo/Desarrollo/dirac_solver/planning/spinor-definition.md#autotoc_md93',1,'Entradas'],['../md_planning_2spinor-definition.html#autotoc_md83',1,'Entradas'],['..//home/sebastian/Documents/Desarrollo/Desarrollo/dirac_solver/planning/spinor-definition.md#autotoc_md89',1,'Entradas']]],
  ['entre_20los_20patrones_18',['9. Relaciones entre los Patrones',['../md_planning_2design-pattern.html#autotoc_md29',1,'']]],
  ['equation_20solver_19',['Presentation Structure: Requirements Engineering for a Dirac Equation Solver',['../md_planning_2requirements-engineering.html',1,'']]],
  ['espinor_20constante_20',['Espinor Constante',['..//home/sebastian/Documents/Desarrollo/Desarrollo/dirac_solver/planning/spinor-definition.md#autotoc_md88',1,'']]],
  ['espinor_20de_20pauli_20general_21',['Construcción del Espinor de Pauli General',['../md_planning_2spinor-definition.html',1,'']]],
  ['espinores_20de_20la_20base_22',['Espinores de la Base',['../md_planning_2spinor-definition.html#autotoc_md85',1,'']]],
  ['esquema_20visual_23',['📂 Esquema Visual',['../md_planning_2structure.html#autotoc_md97',1,'']]],
  ['estructura_20del_20proyecto_20dirac_5fsolver_24',['Estructura del Proyecto dirac_solver',['../md_planning_2structure.html',1,'']]],
  ['evaluate_25',['evaluate',['../classCoulombPotential.html#ae407d6cb33e69a230367685e05c09aaf',1,'CoulombPotential::evaluate()'],['../classdirac__solver_1_1initial__state_1_1GaussianPacket.html#a316c915e47f47aaeb218a90915ab8499',1,'dirac_solver.initial_state.GaussianPacket.evaluate()'],['../classScalarPotential.html#a973bf456bbbcd628816de50515d330fe',1,'ScalarPotential::evaluate()'],['../classPotential.html#a32efd5ee677886223026061411b65538',1,'Potential::evaluate()'],['../classFreeParticle.html#a19b24bf80dcc7268816c455674c0c9c4',1,'FreeParticle::evaluate()']]],
  ['evaluate_5fon_5fgrid_26',['evaluate_on_grid',['../classdirac__solver_1_1initial__state_1_1GaussianPacket.html#a8cfb6b87a64c877fad6f430d9c169a1a',1,'dirac_solver::initial_state::GaussianPacket']]],
  ['examples_20tt_27',['&lt;tt&gt;examples/&lt;/tt&gt;',['../md_planning_2structure.html#autotoc_md112',1,'']]],
  ['extensión_20dinámica_20de_20funcionalidades_28',['7. Patrón Decorator – Extensión Dinámica de Funcionalidades',['../md_planning_2design-pattern.html#autotoc_md25',1,'']]],
  ['extensibilidad_20de_20componentes_20físicos_29',['4. Patrones Template y Factory Method - Extensibilidad de Componentes Físicos',['../md_planning_2design-pattern.html#autotoc_md20',1,'']]],
  ['externas_30',['8. Patrón Adapter – Interoperabilidad con Librerías Externas',['../md_planning_2design-pattern.html#autotoc_md27',1,'']]]
];
